# Generated by Django 4.2.2 on 2023-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birth_date', models.DateField()),
                ('grade', models.CharField(choices=[('B', 'Bachlore'), ('M', 'Master')], default='B', max_length=1)),
                ('registration_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
