# Generated by Django 4.2.2 on 2023-06-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_student_graduation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
